name: _internal_testing
description: An internal testing package for essential_lints.
version: 1.0.0

repository: https://github.com/FMorschel/essential_lints
issue_tracker: https://github.com/FMorschel/essential_lints/issues
license: MIT

publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: any
  analyzer_testing: any

dev_dependencies:
  lints: any
  test: any
