name: _essential_lints_annotations_test
description: A test package for `essential_lints_annotations`.
version: 1.0.0

repository: https://github.com/FMorschel/essential_lints
issue_tracker: https://github.com/FMorschel/essential_lints/issues
license: MIT

publish_to: none

environment:
  sdk: ^3.10.0

dependencies:

dev_dependencies:
  analyzer: ^9.0.0
  dartdoc:
    git:
      url: https://github.com/dart-lang/dartdoc/
      ref: 3f1f09cddec561faaa61ba3dc767b813f6d6c699
  essential_lints_annotations:
    path: ../essential_lints_annotations
  meta: ^1.11.0
  path: ^1.9.1
  test: ^1.26.3
  very_good_analysis: ^10.0.0
