name: _essential_lints_annotations_test
description: A test package for `essential_lints_annotations`.
version: 1.0.0

repository: https://github.com/FMorschel/essential_lints
issue_tracker: https://github.com/FMorschel/essential_lints/issues
license: MIT

publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:

dev_dependencies:
  analyzer: any
  dartdoc:
    git:
      url: https://github.com/dart-lang/dartdoc/
      ref: 3f1f09cddec561faaa61ba3dc767b813f6d6c699
  essential_lints_annotations: any
  meta: any
  path: any
  test: any
