name: essential_dx
description: A collection of essential Dart developer tools to improve the developer experience.
publish_to: none

repository: https://github.com/FMorschel/essential_lints
documentation: https://github.com/FMorschel/essential_lints#readme
issue_tracker: https://github.com/FMorschel/essential_lints/issues
license: MIT

environment:
  sdk: ^3.10.0

workspace:
  - essential_lints
  - _essential_lints_annotations_test
  - _internal_plugin
  - _internal_testing

dependencies:
  analysis_server_plugin: ^0.3.4
  analyzer: 9.0.0
  logging: ^1.3.0
  meta: ^1.11.0

dev_dependencies:
  analyzer_testing: ^0.1.5
  dartdoc:
    git:
      url: https://github.com/dart-lang/dartdoc/
      ref: 3f1f09cddec561faaa61ba3dc767b813f6d6c699
  test: ^1.26.3
  test_reflective_loader: ^0.4.0
  very_good_analysis: ^10.0.0
