name: essential_dx
description: A collection of essential Dart developer tools to improve the developer experience.
publish_to: none

repository: https://github.com/FMorschel/essential_lints
documentation: https://github.com/FMorschel/essential_lints#readme
issue_tracker: https://github.com/FMorschel/essential_lints/issues
license: MIT

environment:
  sdk: ^3.10.0

workspace:
  - essential_lints

dev_dependencies:
  analyzer_testing: ^0.1.4
  test: ^1.26.3
  test_reflective_loader: ^0.4.0
  very_good_analysis: ^10.0.0
