name: essential_lints_annotations
description: Annotations for essential_lints package.
version: 0.1.0

repository: https://github.com/FMorschel/essential_lints
issue_tracker: https://github.com/FMorschel/essential_lints/issues
license: MIT

environment:
  sdk: ">=2.19.0 <4.0.0"

# Recommended keywords help users find the package on pub.dev.
keywords:
  - dart
  - analysis
  - annotations
  - meta

dependencies:
  meta: ^1.11.0

dev_dependencies:
  very_good_analysis: ^10.0.0
