name: essential_lints
description: New lint rules for Dart/Flutter projects and related fixes.
version: 0.1.0

repository: https://github.com/FMorschel/essential_lints
issue_tracker: https://github.com/FMorschel/essential_lints/issues
license: MIT

environment:
  sdk: ^3.10.0

resolution: workspace

# Recommended keywords help users find the package on pub.dev.
keywords:
  - lints
  - dart
  - analysis
  - linters

dependencies:
  analysis_server_plugin: ^0.3.4
  analyzer: 9.0.0
  analyzer_plugin: ^0.13.10
  collection: ^1.19.1
  essential_lints_annotations: ^0.1.0
  logging: ^1.3.0
  meta: ^1.9.0

dev_dependencies:
  _internal_testing:
    path: ../_internal_testing
  analyzer_testing: any
  test: any
  test_reflective_loader: any
  very_good_analysis: any
