name: essential_lints
description: New lint rules for Dart/Flutter projects and related fixes.
version: 0.0.1

repository: https://github.com/FMorschel/essential_lints
issue_tracker: https://github.com/FMorschel/essential_lints/issues
license: MIT

environment:
  sdk: ^3.10.0

resolution: workspace

# Recommended keywords help users find the package on pub.dev.
keywords:
  - lints
  - dart
  - analysis
  - linters

dependencies:
  analysis_server_plugin: ^0.3.3
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.10
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  analyzer_testing: any
  test: any
  test_reflective_loader: any
  very_good_analysis: any
