name: _internal_plugin
description: An internal plugin package for essential_lints.

version: 1.0.0

publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.4
  analyzer: ^9.0.0
  essential_lints:
    path: ../essential_lints
  essential_lints_annotations:
    path: ../essential_lints_annotations
  logging: ^1.3.0
  meta: ^1.17.0

dev_dependencies:
  _internal_testing:
    path: ../_internal_testing
  analyzer_testing: ^0.1.7
  lints: any
  test: any
  test_reflective_loader: ^0.4.0
